# This default does not deploy anyything useful without adding values from one of the files in the valuesd directory
# Example install:
# helm install mods-auth bvb-repo/modules -f global-values.yaml -f modules/valuesd/<RELEASE_TAG>-auth.yaml
noInitJobs: false
defaultValues:
  backend_modules: 
    resources:
      requests:
        memory: "715827883"
      limits:
        memory: "715827883"
# these are default global values. Overwrite as needed
global:
  db:
    host: folio-zal-pg 
    port: 5432
    folioSecret: db-connect-folio
    okapiSecret: db-connect-okapi
    adminSecret: pg-superuser-secret
    allModuleAccess: true
  kafka:
    serviceName: kafka
    port: 9092
    allModuleAccess: true
  elasticsearch:
    serviceName: elasticsearch 
    port: 9200
  s3storage:
    secretName: s3storage-access
  okapi:
    serviceName: okapi
    secureSupertenant: True
    port: 9130
    repositoryName: okapi
  image:
    pullsecret: gitlab-folio-group
    repositoryBaseUrl: gitlab.bib-bvb.de:5050/folio-public/
    folioToolsTag: "debian-v1.3-debug2"
    okapicliRepo: okapiclient
    okapicliTag: "v0.21"
  backend_modules:
    defaultReplicaCount: "1"
    SELF_INTRODUCE: "true"
    shortNames: "false"
  folio:
    release: "poppy"
    tag: "2023-2"
    subtag: "GA"
    env: "poppy-test"

