apiVersion: v1
kind: Service
metadata:
  name: {{ include "vufind.fullname" . }}
  labels:
    {{- include "vufind.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.shibboleth.enabled }}
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
    {{- end }}
  selector:
    {{- include "vufind.selectorLabels" . | nindent 4 }}
