{{- if .Values.shibboleth.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-shibboleth
data:
  shibboleth2.xml: |
    <SPConfig xmlns="urn:mace:shibboleth:2.0:native:sp:config" xmlns:conf="urn:mace:shibboleth:2.0:native:sp:config" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" clockSkew="180">
        <ApplicationDefaults entityID="{{ include "vufind.shib.entityId" . }}" REMOTE_USER="{{ .Values.shibboleth.remoteuser }}">
        <Sessions lifetime="28800" timeout="3600" relayState="ss:mem" checkAddress="false" handlerSSL="true" cookieProps="https" idpHistory="true" redirectLimit="exact">
            <SSO entityID="{{ .Values.shibboleth.idpEntityId }}" forceAuthn="false" >
            SAML2
            </SSO>
            <Logout asynchronous="false">SAML2 Local</Logout>
            <Handler type="MetadataGenerator" Location="/Metadata" signing="false"/>
            <Handler type="MetadataGenerator" Location="/Metadata.xml" signing="false" />
            <Handler type="Status" Location="/Status" acl="192.0.2.0/24 127.0.0.1 ::1" />
            <Handler type="Session" Location="/Session" showAttributeValues="true" />
            <Handler type="DiscoveryFeed" Location="/DiscoFeed" />
        </Sessions>
        <Errors supportContact="{{ .Values.shibboleth.supportContact }}" helpLocation="/about.html" styleSheet="/shibboleth-sp/main.css" />
        <MetadataProvider type="XML" url="{{ .Values.shibboleth.metadataProviderURL }}" backingFilePath="Metadata-backingfile.xml" maxRefreshDelay="3600" legacyOrgNames="true">
        </MetadataProvider>
        <AttributeExtractor type="XML" validate="true" reloadChanges="false" path="attribute-map.xml"/>
        <AttributeResolver type="Query" subjectMatch="true"/>
        <AttributeFilter type="XML" validate="true" path="attribute-policy.xml"/>
        <CredentialResolver type="Chaining">
            {{- range .Values.shibboleth.credentialResolverCerts }}
            <CredentialResolver type="File" use="{{ .use }}" certificate="{{ .name }}.crt" key="{{ .name }}.key" />
            {{- end }}
        </CredentialResolver>
        <RelyingParty Name="{{ .Values.shibboleth.idpEntityId }}" signing="true" />
        </ApplicationDefaults>
        <SecurityPolicyProvider type="XML" validate="true" path="security-policy.xml"/>
        <ProtocolProvider type="XML" validate="true" reloadChanges="false" path="protocols.xml"/>
    </SPConfig>
  attribute-map.xml: |
    <Attributes xmlns="urn:mace:shibboleth:2.0:attribute-map" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

        <!-- First some useful eduPerson attributes that many sites might use. -->

        <Attribute name="urn:mace:dir:attribute-def:eduPersonPrincipalName" id="eduPersonPrincipalName">
                <AttributeDecoder xsi:type="ScopedAttributeDecoder" />
        </Attribute>

        <Attribute name="urn:oid:1.3.6.1.4.1.5923.1.1.1.6" id="eduPersonPrincipalName">
                <AttributeDecoder xsi:type="ScopedAttributeDecoder" />
        </Attribute>


        <Attribute name="urn:mace:dir:attribute-def:eduPersonScopedAffiliation" id="eduPersonScopedAffiliation">
                <AttributeDecoder xsi:type="ScopedAttributeDecoder" caseSensitive="false" />
        </Attribute>

        <Attribute name="urn:oid:1.3.6.1.4.1.5923.1.1.1.9" id="eduPersonScopedAffiliation">
                <AttributeDecoder xsi:type="ScopedAttributeDecoder" caseSensitive="false" />
        </Attribute>


        <Attribute name="urn:mace:dir:attribute-def:eduPersonAffiliation" id="eduPersonAffiliation">
                <AttributeDecoder xsi:type="StringAttributeDecoder" caseSensitive="false" />
        </Attribute>

        <Attribute name="urn:oid:1.3.6.1.4.1.5923.1.1.1.1" id="eduPersonAffiliation">
                <AttributeDecoder xsi:type="StringAttributeDecoder" caseSensitive="false" />
        </Attribute>


        <Attribute name="urn:mace:dir:attribute-def:eduPersonPrimaryAffiliation" id="eduPersonPrimaryAffiliation">
        </Attribute>

        <Attribute name="urn:oid:1.3.6.1.4.1.5923.1.1.1.5" id="eduPersonPrimaryAffiliation">
                <AttributeDecoder xsi:type="StringAttributeDecoder" caseSensitive="false" />
        </Attribute>

        <Attribute name="urn:oid:1.2.840.113556.1.2.431" id="extensionAttribute9">
          <AttributeDecoder xsi:type="StringAttributeDecoder" caseSensitive="false" />
        </Attribute>

        <Attribute name="urn:mace:dir:attribute-def:eduPersonEntitlement" id="eduPersonEntitlement" />
        <Attribute name="urn:oid:1.3.6.1.4.1.5923.1.1.1.7" id="eduPersonEntitlement" />

        <!-- A persistent id attribute that supports personalized anonymous access. -->

        <!-- First, the deprecated version: -->
        <Attribute name="urn:mace:dir:attribute-def:eduPersonTargetedID" id="eduPersonTargetedID">
                <AttributeDecoder xsi:type="ScopedAttributeDecoder" />
        </Attribute>

        <!-- Second, the new version (note the OID-style name): -->
        <Attribute name="urn:oid:1.3.6.1.4.1.5923.1.1.1.10" id="persistent-id">
                <AttributeDecoder xsi:type="NameIDAttributeDecoder" formatter="$NameQualifier!$SPNameQualifier!$Name" />
        </Attribute>


        <!-- Third, the SAML 2.0 NameID Format: -->
        <Attribute name="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent" id="persistent-id">
                <AttributeDecoder xsi:type="NameIDAttributeDecoder" formatter="$NameQualifier!$SPNameQualifier!$Name" />
        </Attribute>

        <Attribute name="urn:mace:dir:attribute-def:eduPersonNickname" id="nickname" />
        <Attribute name="urn:mace:dir:attribute-def:eduPersonPrimaryOrgUnitDN" id="primary-orgunit-dn" />
        <Attribute name="urn:mace:dir:attribute-def:eduPersonOrgUnitDN" id="orgunit-dn" />
        <Attribute name="urn:mace:dir:attribute-def:eduPersonOrgDN" id="org-dn" />


        <Attribute name="urn:oid:1.3.6.1.4.1.5923.1.1.1.2" id="nickname" />
        <Attribute name="urn:oid:1.3.6.1.4.1.5923.1.1.1.8" id="primary-orgunit-dn" />
        <Attribute name="urn:oid:1.3.6.1.4.1.5923.1.1.1.4" id="orgunit-dn" />
        <Attribute name="urn:oid:1.3.6.1.4.1.5923.1.1.1.3" id="org-dn" />

        <Attribute name="urn:mace:dir:attribute-def:mail" id="mail" />
        <Attribute name="urn:mace:dir:attribute-def:o" id="o" />
        <Attribute name="urn:mace:dir:attribute-def:ou" id="ou" />
        <Attribute name="urn:mace:dir:attribute-def:sn" id="sn" />
        <Attribute name="urn:mace:dir:attribute-def:givenName" id="givenName" />


        <Attribute name="urn:oid:2.5.4.4" id="sn" />
        <Attribute name="urn:oid:2.5.4.42" id="givenName" />
        <Attribute name="urn:oid:0.9.2342.19200300.100.1.3" id="mail" />
        <Attribute name="urn:oid:2.5.4.10" id="o" />
        <Attribute name="urn:oid:2.5.4.11" id="ou" />

        <Attribute name="urn:mace:terena.org:attribute-def:schacPersonalUniqueCode" id="schacPersonalUniqueCode" />
        <Attribute name="urn:oid:1.3.6.1.4.1.25178.1.2.14" id="schacPersonalUniqueCode" />

        <Attribute name="urn:mace:terena.org:attribute-def:schacGender" id="schacGender" />
        <Attribute name="urn:oid:1.3.6.1.4.1.25178.1.2.2" id="schacGender" />

        <Attribute name="urn:mace:dir:attribute-def:cn" id="cn" />

        <Attribute name="urn:mace:dir:attribute-def:uid" id="uid" />
        <Attribute name="urn:oid:0.9.2342.19200300.100.1.1" id="uid" />

        <Attribute name="urn:mace:dir:attribute-def:sAMAccountName" id="sAMAccountName" />
        <Attribute name="urn:oid:1.2.840.113556.1.4.221" id="sAMAccountName" />

        <Attribute name="urn:mace:dir:attribute-def:telephoneNumber" id="telephoneNumber" />
        <Attribute name="urn:mace:dir:attribute-def:title" id="title" />
        <Attribute name="urn:mace:dir:attribute-def:initials" id="initials" />
        <Attribute name="urn:mace:dir:attribute-def:description" id="description" />
        <Attribute name="urn:mace:dir:attribute-def:carLicense" id="carLicense" />
        <Attribute name="urn:mace:dir:attribute-def:departmentNumber" id="departmentNumber" />
        <Attribute name="urn:mace:dir:attribute-def:displayName" id="displayName" />
        <Attribute name="urn:mace:dir:attribute-def:employeeNumber" id="employeeNumber" />
        <Attribute name="urn:mace:dir:attribute-def:employeeType" id="employeeType" />
        <Attribute name="urn:mace:dir:attribute-def:preferredLanguage" id="preferredLanguage" />
        <Attribute name="urn:mace:dir:attribute-def:manager" id="manager" />
        <Attribute name="urn:mace:dir:attribute-def:seeAlso" id="seeAlso" />
        <Attribute name="urn:mace:dir:attribute-def:facsimileTelephoneNumber" id="facsimileTelephoneNumber" />
        <Attribute name="urn:mace:dir:attribute-def:street" id="street" />
        <Attribute name="urn:mace:dir:attribute-def:postOfficeBox" id="postOfficeBox" />
        <Attribute name="urn:mace:dir:attribute-def:postalCode" id="postalCode" />
        <Attribute name="urn:mace:dir:attribute-def:st" id="st" />
        <Attribute name="urn:mace:dir:attribute-def:l" id="l" />
        <Attribute name="urn:mace:dir:attribute-def:businessCategory" id="businessCategory" />
        <Attribute name="urn:mace:dir:attribute-def:physicalDeliveryOfficeName" id="physicalDeliveryOfficeName" />
        <Attribute name="urn:oid:2.5.4.3" id="cn" />
        <Attribute name="urn:oid:2.5.4.20" id="telephoneNumber" />
        <Attribute name="urn:oid:2.5.4.12" id="title" />
        <Attribute name="urn:oid:2.5.4.43" id="initials" />
        <Attribute name="urn:oid:2.5.4.13" id="description" />
        <Attribute name="urn:oid:2.16.840.1.113730.3.1.1" id="carLicense" />
        <Attribute name="urn:oid:2.16.840.1.113730.3.1.2" id="departmentNumber" />
        <Attribute name="urn:oid:1.2.840.113556.1.2.141" id="department" />
        <Attribute name="urn:oid:2.16.840.1.113730.3.1.241" id="displayName" />
        <Attribute name="urn:oid:1.2.840.113556.1.2.610" id="employeeNumber" />
        <Attribute name="urn:oid:2.16.840.1.113730.3.1.4" id="employeeType" />
        <Attribute name="urn:oid:2.16.840.1.113730.3.1.39" id="preferredLanguage" />
        <Attribute name="urn:oid:0.9.2342.19200300.100.1.10" id="manager" />
        <Attribute name="urn:oid:2.5.4.34" id="seeAlso" />
        <Attribute name="urn:oid:2.5.4.23" id="facsimileTelephoneNumber" />
        <Attribute name="urn:oid:2.5.4.9" id="street" />
        <Attribute name="urn:oid:2.5.4.18" id="postOfficeBox" />
        <Attribute name="urn:oid:2.5.4.17" id="postalCode" />
        <Attribute name="urn:oid:2.5.4.8" id="st" />
        <Attribute name="urn:oid:2.5.4.7" id="l" />
        <Attribute name="urn:oid:2.5.4.15" id="businessCategory" />
        <Attribute name="urn:oid:2.5.4.19" id="physicalDeliveryOfficeName" />

        <Attribute name="urn:oid:1.3.6.1.4.1.5923.1.1.1.13" id="eduPersonUniqueId">
                <AttributeDecoder xsi:type="ScopedAttributeDecoder" caseSensitive="false" />
        </Attribute>

        <Attribute name="urn:mace:dir:attribute-def:eduPersonUniqueId" id="eduPersonUniqueId">
                    <AttributeDecoder xsi:type="ScopedAttributeDecoder" caseSensitive="false" />
        </Attribute>

    </Attributes>
  default-ssl.conf: |
    <VirtualHost *:443>
        ServerName https://{{ (first .Values.ingress.hosts).host }}
        UseCanonicalName On
        DocumentRoot /var/www/html
        ErrorLog /proc/self/fd/2
        CustomLog /proc/self/fd/1 combined
        SSLEngine on
        SSLCertificateFile      /etc/ssl/certs/servercert.pem
        SSLCertificateKeyFile   /etc/ssl/private/servercert.key
        <FilesMatch "\.(?:cgi|shtml|phtml|php)$">
                SSLOptions +StdEnvVars
        </FilesMatch>
        <Directory /usr/lib/cgi-bin>
                SSLOptions +StdEnvVars
        </Directory>
    </VirtualHost>
{{- end }}





