{{- if .Values.shibboleth.enabled }}
  {{- range .Values.shibboleth.credentialResolverCerts }}
    {{- if .generate }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Release.Name | trunc 63 | trimSuffix "-" }}-{{ .name }}
spec:
  secretName: {{ $.Release.Name | trunc 63 | trimSuffix "-" }}-{{ .name }}

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

  duration: 26300h # 3 years
  renewBefore: 720h # 30d


  subject:
    organizations:
      - shibboleth
  commonName: {{ (first $.Values.ingress.hosts).host | quote }}
  dnsNames:
    {{- range $.Values.ingress.hosts }}
    - {{ .host | quote }}
    {{- end }}
  issuerRef:
    name: {{ .Issuer }}
    kind: {{ .IssuerType | default "Issuer" }}

    {{- end }}
  {{- end }}
{{- end }}