apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ include "vufind.dbhostname" . | quote }}
spec:
  teamId: {{ (($.Values.global).vufinddb).teamId | default "vufind" }}
  volume:
    size: {{ .Values.volumeSize | default "5Gi" }}
    storageClass: {{ .Values.storageClass | default "" | quote }}
  resources:
    {{- toYaml $.Values.resources | nindent 4 }}
  numberOfInstances: {{ $.Values.numberOfInstances | default "3"  }}
  enableShmVolume: true
  users:
    clustersuperuser:
    - superuser
    - login
    - createdb
  {{- if and .Values.backup .Values.backup.logicalEnable }}
  enableLogicalBackup: true
  logicalBackupSchedule: {{ .Values.backup.logicalSchedule | default "30 00 * * *" | quote }}
  {{- end }}
  {{- if and .Values.backup .Values.backup.wal_s3_bucket }} 
  env:
  - name: WAL_S3_BUCKET
    value: {{ .Values.backup.wal_s3_bucket | default "" | quote }}
  {{- end }}
  postgresql:
    version: {{ .Values.version | default "15" | quote }}
    parameters:
      {{- toYaml $.Values.parameters | nindent 6 }}
  patroni:
    pg_hba:
      - local   replication    standby            trust
      - local   all            all                trust
      - host    replication    standby  all       md5
      - hostssl all all 0.0.0.0/0 md5
      - host    all            all      all       md5
  nodeAffinity:
    {{- toYaml $.Values.nodeAffinity | nindent 6 }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 6 }}
  {{- end }}
    

