# Source: zalando-pg/templates/postgresql.yaml
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: "folio-zal-pg"
spec:
  teamId: folio
  volume:
    size: 5Gi
    storageClass: "local-path"
  resources:
    limits:
      cpu: "8"
      memory: 16Gi
    requests:
      cpu: "4"
      memory: 4Gi
  numberOfInstances: 2
  enableShmVolume: true
  users:
    clustersuperuser:
    - superuser
    - login
    - createdb
  postgresql:
    version: "13"
    parameters:
      archive_mode: "off"
      archive_timeout: "0"
      checkpoint_timeout: 5min
      datestyle: iso, dmy
      db_user_namespace: "off"
      default_text_search_config: pg_catalog.german
      effective_cache_size: 4GB
      effective_io_concurrency: "1"
      lc_messages: C
      lc_monetary: de_DE.UTF-8
      lc_numeric: de_DE.UTF-8
      lc_time: de_DE.UTF-8
      listen_addresses: '*'
      log_line_prefix: '%m [%p] %q%u@%d '
      log_timezone: Europe/Berlin
      maintenance_work_mem: 64MB
      max_connections: "100"
      max_locks_per_transaction: "64"
      max_prepared_transactions: "0"
      max_replication_slots: "10"
      max_wal_senders: "10"
      max_wal_size: 1GB
      max_worker_processes: "8"
      password_encryption: md5
      shared_buffers: 128MB
      temp_buffers: 8MB
      timezone: Europe/Berlin
      wal_keep_segments: "0"
      wal_level: replica
      wal_log_hints: "off"
      work_mem: 4MB
  patroni:
    pg_hba:
      - local   replication    standby            trust
      - local   all            all                trust
      - host    replication    standby  all       md5
      - hostssl all all 0.0.0.0/0 md5
      - host    all            all      all       md5
---
