# provide image pull secret for folio-tools if needed
imagePullSecrets: 
- name: folio-hbz-dockerhub-key

image:
  folioToolsTag: debian-v1.3
  okapicliRepo: okapiclient
  okapicliTag: v0.17
  repositoryBaseUrl: gitlab.bib-bvb.de:5050/folio-public/
  stripesBaseUrl: gitlab.bib-bvb.de:5050/folio-public/
  pullPolicy: IfNotPresent

# kubernetes resources. Note: adjust postgres parameters bellow accordingly!
# (e.g. shared_buffers, effective_cache_size)
resources:
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# IMPORTANT: For some reason, there are default limits set by the zalando operator currently.
# These are too small to actually run postgres! Therefore, default values are set here.
# Adjust to your liking!
  requests:
    cpu: "100m"
    memory: "2Gi"
  limits:
    cpu: "2"
    memory: "16Gi"

teamId: "folio"
numberOfInstances: 2

# postgresql parameters
parameters:
  listen_addresses: "*"
  max_connections: "100"
  password_encryption: "md5"
  db_user_namespace: "off"
  shared_buffers: "128MB"
  temp_buffers: "8MB"
  max_prepared_transactions: "0"
  work_mem: "4MB"
  maintenance_work_mem: "64MB"
  effective_io_concurrency: "1"
  max_worker_processes: "8"

  wal_level: "replica"
  wal_log_hints: "off"
  checkpoint_timeout: "5min"
  max_wal_size: "1GB"
  archive_mode: "off"
  archive_timeout: "0"
  max_wal_senders: "10"
  max_replication_slots: "10"
  wal_keep_segments: "0"
  effective_cache_size: "4GB"

  log_line_prefix: "%m [%p] %q%u@%d "
  log_timezone: 'Europe/Berlin'
  datestyle: "iso, dmy"
  timezone: 'Europe/Berlin'
  lc_messages: 'C'
  # lc_monetary: 'de_DE.utf8'
  # lc_numeric: 'de_DE.utf8'
  # lc_time: 'de_DE.utf8'
  default_text_search_config: 'pg_catalog.german'

  max_locks_per_transaction: "64"

# affinity rules TODO: convert to best practice setting per "toYaml" as above for more flexibility
affinityEnabled: false
affinityKey: "disk"
affinityValue: "ssd"

backup:
  logicalEnable: false
  # logicalSchedule: "30 00 * * *"
  # Values for pg_basebackups and WAL backups. If bucket is not set, backups will not run.
  # walS3Bucket: bucketnnameForPGBasebackupAndWals
  # backupSchedule: BACKUP_SCHEDULE: "10 17 * * MON"
  # backupNumRetain: 4
