teamId: "folio"
numberOfInstances: 3
# kubernetes resources. Note: adjust postgres parameters bellow accordingly!
# (e.g. shared_buffers, effective_cache_size)
resources:
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# IMPORTANT: For some reason, there are default limits set by the zalando operator currently.
# These are too small to actually run postgres! Therefore, default values are set here.
# Adjust to your liking!
  requests:
    cpu: "4"
    memory: "4Gi"
  limits:
    cpu: "16"
    memory: "16Gi"

# postgresql parameters
parameters:
  listen_addresses: "*"
  # max_wal_senders: "10"
  # max_wal_size: 4GB
  max_connections: "1200"
  # shared_buffers: "128MB"
  db_user_namespace: "off"
  password_encryption: "md5"
  effective_io_concurrency: "2"
  max_locks_per_transaction: "64"
  max_prepared_transactions: "0"
  max_replication_slots: "10"
  temp_buffersi: "128MB"
  wal_keep_segments: "32"
  wal_level: "replica"
  wal_log_hints: "true"
  archive_mode: "on"
  archive_timeout: "120"
  checkpoint_timeout: "3000"
  effective_cache_size: "24GB"
  maintenance_work_mem: "256MB"
  max_replication_slots: "0"
  max_wal_senders: "10"
  max_wal_size: "10GB"
  max_worker_processes: "12"
  shared_buffers: "16GB"
  temp_buffers: "256MB"
  # wal_level: "minimal"
  work_mem: "256MB"

# affinity rules TODO: convert to best practice setting per "toYaml" as above for more flexibility
affinityEnabled: false
affinityKey: "disk"
affinityValue: "ssd"

backup:
  logicalEnable: false
  # logicalSchedule: "30 00 * * *"
  customWalS3Bucket: false
