---
# if okapi is deployed in the same namespace, the url will be configured automatically
# okapihost: "okapi"
# okapiport: "9130"
# okapihttp: "http"
# this generates the url: http://okapi:9130

# We usually define a path for accessing okapi within the same base URL where stripes is loaded.
# So you load stripes from https://my-domain.tld , then Okapi API gateway will be accessible
# on https://my-domain.tld/okapi
# okapiIngressPath: "/okapi"

imagePullSecrets: []

image:
  folioToolsTag: debian-v1.3-debug2
  okapicliRepo: okapiclient
  okapicliTag: v0.21
  repositoryBaseUrl: gitlab.bib-bvb.de:5050/folio-public/
  stripesBaseUrl: gitlab.bib-bvb.de:5050/folio-public/
  pullPolicy: IfNotPresent
  # here you can overwrite the stripes image tag
  stripesTag: "poppy-csp2-complete-2"


#
# List of Folio Tenants to install
tenants:
- description: Danish Library Technology Institute diku
  # add extra frontend modules
  frontendmodulesExtras: []
  # ingress definition
  ingress:
    annotations: []
      # cert-manager.io/cluster-issuer: letsencrypt
      # nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/24,172.10.0.1
    # 
    # enable ingress for okapi and stripes
    enable: false
    #
    # define ingres Class name. Defaults to "nginx"
    # classname: nginx
    # 
    # this makes it impossible to manipulate X-Okapi-Tenant HTTP headers.
    # only works with ingress-nginx controller with the option 
    # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#allow-snippet-annotations
    # set to true
    secureOkapi: false
    #
    # Hostname for stripes
    host: folio-k8s1.folio.hbz-nrw.de
    #
    path: /
    # 
    # If you want to use tls with certmanager
    #tls:
    #  - host: folio.example.com
    #    secretName: folio-tls-secret
  #
  # wether to load reference and sample data
  loadReference: true
  loadSample: false
  name: Datalogisk Institut diku
  tenantId: diku
  clientAdminAccount: admin
  # register tenant in Okapi
  register: true
  # email configuration
  email: {}
  #  port: 25
  #  loginOption: DISABLED
  #  username: folio
  #  password: password
  #  trustAll: true
  #  smtpHost: smtp.example.com
  #  from: folio@example.com
  # Deploy stripes nginx container
  stripes:
    enable: true
    logoUrl: "https://www.folio.org/wp-content/uploads/2018/09/FOLIO_Logo.png"
    faviconUrl: "https://www.folio.org/wp-content/uploads/2018/09/FOLIO_Logo.png"
    nodeSelector: {}
    affinity: {}   
    replicaCount: 1
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 50Mi
    serviceType: ClusterIP
    tolerations: []
  
