{{ range .Values.tenants }}
{{ if .clientAdminAccount }}
{{ $secretName := printf "%s-%s-password" .tenantId .clientAdminAccount }}
{{- if not (lookup "v1" "Secret" $.Release.Namespace $secretName ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  password: {{ randAlphaNum 16 }}
{{- end }}
{{- end }}
{{- end }}
