{{range .Values.tenants}}
{{- if .register }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Release.Name }}-preset-values-{{ .tenantId }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "10" 
spec:
  template:
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ $.Chart.Name }}-preset-values-{{ .tenantId }}
        {{- with $.Values.image }}
        image: {{ .repositoryBaseUrl }}{{ .okapicliRepo }}:{{ .okapicliTag }}
        imagePullPolicy: {{ .pullPolicy }}
        {{- end }}
        volumeMounts:
        - name: scripts
          mountPath: "/usr/src/app/kube-scripts"
        envFrom:
        - configMapRef:
            name: {{ $.Release.Name }}-preset-{{.tenantId}}-env
        env:
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .tenantId }}-admin-pwd
              key: password
        command:
          - kube-scripts/Preset_values.sh
      restartPolicy: Never
      volumes:
      - name: scripts
        configMap:
          name: {{ $.Release.Name }}-scripts
          defaultMode: 0555
          optional: false
  backoffLimit: 10
{{- end }}
---
{{- end }}
