{{- range .Values.tenants }}
{{- if .register }}
{{- if not (lookup "v1" "Secret" $.Release.Namespace (printf "%s-admin-pwd" .tenantId) ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .tenantId }}-admin-pwd
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  password: {{ .adminPassword | default (randAlphaNum 12 | b64enc) }}
---
{{- end }}
{{- end }}
{{- end }}
