{{- if not (lookup "v1" "Secret" $.Release.Namespace "folio-db-secret" ) }}
apiVersion: v1
kind: Secret
metadata:
  name: folio-db-secret
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  #OKAPI_PASSWORD: {{ $.Values.global.db.okapiPassword | b64enc | quote }}
  OKAPI_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}
  FOLIO_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
# {{- if not (lookup "v1" "Secret" $.Release.Namespace "okapi-conf" ) }}
# apiVersion: v1
# kind: Secret
# metadata:
#   name: okapi-config
#   annotations:
#     "helm.sh/resource-policy": "keep"
# type: Opaque
# stringData:
#   okapi-config.json: |
#     {
#         "okapiurl": "http://okapi:9130",
#         "postgres_database": "okapi",
#         "postgres_host": "folio-zal-pg",
#         "postgres_password": {{ $.Values.global.db.okapiPassword | quote }},
#         "postgres_username": "okapi",
#         "storage": "postgres"
#     }
# {{- end }}
