{{- if not (lookup "v1" "Secret" $.Release.Namespace "folio-db-secret" ) }}
apiVersion: v1
kind: Secret
metadata:
  name: folio-db-secret
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  OKAPI_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}
  FOLIO_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
