{{- if not (lookup "v1" "Secret" $.Release.Namespace $.Values.global.db.adminSecret ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.global.db.adminSecret }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  PGSU_PASSWORD: {{ randAlphaNum 48 | b64enc | quote }}
{{- end }}
