apiVersion: batch/v1
kind: Job
metadata:
  name: create-pgsuperuser
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
spec:
  template:
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: create-pg-superuser
        image: {{ $.Values.image.repositoryBaseUrl }}folio-tools:{{ $.Values.image.folioToolsTag }} 
        imagePullPolicy:  "IfNotPresent"
        env:
        - name: PG_HOST
          valueFrom:
            secretKeyRef:
              name: db-connect-folio
              key: DB_HOST
        - name: PG_DB
          valueFrom:
            secretKeyRef:
              name: db-connect-folio
              key: DB_DATABASE
        - name: PG_PORT
          valueFrom:
            secretKeyRef:
              name: db-connect-folio
              key: DB_PORT
        - name: PG_USER
          value: postgres
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres.{{ .Values.teamId }}-{{ .Release.Name }}.credentials.postgresql.acid.zalan.do 
              key: password
        envFrom:
        - secretRef:
            name: {{ $.Values.global.db.adminSecret }}
        args: ["kube-scripts/create-pgsuperuser.sh"]
        volumeMounts:
        - name: scriptvolume
          mountPath: "/usr/src/app/kube-scripts"
      volumes:
      - name: scriptvolume
        configMap:
          name: {{ $.Release.Name }}-scripts
          defaultMode: 0555
          optional: false
      restartPolicy: Never
  backoffLimit: 3
  ttlSecondsAfterFinished: 300
---
