{{range .Values.backend_modules -}}
{{- if .secretEnv }}
{{ $customSecretName := printf "%s-env" .name }}
{{- if not (lookup "v1" "Secret" $.Release.Namespace $customSecretName ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $customSecretName }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  {{- range .secretEnv }}
  {{ .key }}: {{ .value | default (randAlphaNum 32) }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
