{{- if .Values.global.okapi.secureSupertenant }}
{{- if not (lookup "v1" "Secret" $.Release.Namespace "supertenant-secret" ) }}
apiVersion: v1
kind: Secret
metadata:
  name: supertenant-secret
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  password: {{ randAlphaNum 32 | b64enc }}
{{- end }}
{{- end }}
